#!/usr/bin/expect

spawn su root -c "apt-get install slapd -y"

# LDAP administrator password for user "admin"
expect "Administrator password:"
send "admin\n"
expect "Confirm password:"
send "admin\n"

expect eof